// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
// Generated by: bun run scripts/generate-components.ts
// Re-exports the registry-component so `@/components/beste/component/{name}`
// resolves at dev time to the same path the shadcn CLI installs to.

export * from "@/registry-components/text8/text8";
