/**
 * Public-build site links.
 *
 * Pricing, referrals and accounts are part of the hosted site, not of this
 * repository, so those routes are absent here rather than broken. Pointing them
 * at ui.beste.co keeps every header, footer and docs page that references them
 * identical to the private build's, and sends the reader somewhere real.
 */

export const HOSTED_SITE = "https://ui.beste.co";

/**
 * Always the hosted registry, never this deployment.
 *
 * The private build derives this from an environment variable and falls back
 * to a dev server. Here there is no such variable, so the fallback would win
 * and every install command, canonical and JSON-LD URL on a public clone would
 * point at a port nobody is running.
 */
export const SITE_ORIGIN = HOSTED_SITE;

/**
 * Radix, because that is what this repository contains. The Base UI variant is
 * generated by a codemod that is not part of the public build, so offering it
 * as the default would hand out a command for sources that are not here.
 * ui.beste.co serves both, and its own default stays "base".
 */
export const DEFAULT_FLAVOR: "base" | "radix" = "radix";

/**
 * One flavor, because this repository holds one set of sources. The Base UI
 * variant is produced by a codemod that is not part of the public build, so
 * with a single option the picker hides itself rather than offering a choice
 * that resolves to nothing. ui.beste.co serves both.
 */
export const FLAVOR_OPTIONS: readonly ("base" | "radix")[] = ["radix"];

export const PRICING_HREF = `${HOSTED_SITE}/pricing`;
export const REFERRALS_HREF = `${HOSTED_SITE}/referrals`;
export const ACCOUNT_HREF = `${HOSTED_SITE}/account`;
export const FAVORITES_HREF = `${HOSTED_SITE}/favorites`;

export const PAGES_HREF = `${HOSTED_SITE}/pages`;
export const BLOG_HREF = `${HOSTED_SITE}/blog`;
export const TOOLS_HREF = `${HOSTED_SITE}/tools`;
export const DOCS_HREF = `${HOSTED_SITE}/docs`;
export const DOCS_INSTALLATION_HREF = `${HOSTED_SITE}/docs/installation`;
export const DOCS_MCP_HREF = `${HOSTED_SITE}/docs/mcp`;
export const CHANGELOG_HREF = `${HOSTED_SITE}/changelog`;

export const HOSTED_LINKS_ARE_EXTERNAL = true;

/**
 * Everything the hosted site serves and this build does not. A reader who
 * follows an old link, a search result or a bookmark to one of these should be
 * pointed at the real page rather than shown a dead end.
 */
export const HOSTED_ONLY_PATHS: readonly string[] = [
  "/pricing",
  "/referrals",
  "/account",
  "/favorites",
  "/docs",
  "/changelog",
  "/blog",
  // The free tools are a hosted traffic surface, not part of the library.
  "/tools",
  // The pages tier composes Pro blocks, so it is hosted-only in full: the
  // listing, the detail route and the embed all live on ui.beste.co.
  "/pages",
  "/page",
  // Most of the catalogue is Pro, so a block detail page that is missing here
  // is almost always one that exists on the hosted site rather than a typo.
  // Pieces and components are all present, so a miss there is a real 404.
  "/block",
];

export const hostedLinkProps: { target?: "_blank"; rel?: "noreferrer" } = {
  target: "_blank",
  rel: "noreferrer",
};
