// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
// Generated by: bun run scripts/generate-components.ts
// Re-exports the registry-piece so `@/components/beste/piece/{name}`
// resolves at dev time to the same path the shadcn CLI installs to.

export * from "@/registry-pieces/realestate7/realestate7";
