/**
 * Generates lib/block-sets.ts: which blocks belong to which studio set.
 *
 * There is no `set` field in BlockMeta, and there deliberately is not one in the
 * titles or descriptions either — a set name is an internal label and has no place
 * in what a reader or a search engine sees. So membership is read back out of the
 * blocks themselves, from two signals:
 *
 * 1. The set's own components. Each language ships with its own eyebrow and pill
 *    button, and a block built in that language declares them in its meta. This is
 *    the primary signal: it is machine-readable, it is in the meta rather than the
 *    prose, and it holds for every block in the set including the ones whose demo
 *    copy is a product screen with no studio name in it.
 * 2. The studio name in the demo copy, for the blocks that carry no set component
 *    at all — footers and navbars mostly, which are built from plain markup.
 *
 * A block claimed by one set's components is never pulled into another by a stray
 * mention of that studio in its copy.
 *
 * Usage: bun run scripts/generate-block-sets.ts
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const REGISTRY_DIR = join(import.meta.dirname, "..", "registry");
const OUTPUT = join(import.meta.dirname, "..", "lib", "block-sets.ts");

/**
 * The sets, the components each one is built from, and the word that identifies
 * it in demo copy.
 */
const SETS = [
  { key: "auralis", brand: "Auralis", components: ["badge7", "button12"] },
  { key: "polaris", brand: "Polaris", components: ["badge6", "button1"] },
  { key: "sirius", brand: "Sirius", components: ["badge23", "button21"] },
] as const;

/** Blocks that belong to a set but carry neither its components nor its name. */
const EXTRA: Record<string, string[]> = {
  auralis: [],
  polaris: [],
  sirius: [],
};

/** The registry-components a block declares in its meta. */
function declaredComponents(dir: string): string[] {
  const file = join(REGISTRY_DIR, dir, `${dir}.meta.ts`);
  if (!existsSync(file)) return [];

  const match = /registryComponents\s*:\s*\[(.*?)\]/s.exec(readFileSync(file, "utf-8"));
  if (!match?.[1]) return [];

  return Array.from(match[1].matchAll(/["']([^"']+)["']/g), (m) => m[1] ?? "");
}

const dirs = readdirSync(REGISTRY_DIR).filter((dir) =>
  existsSync(join(REGISTRY_DIR, dir, `${dir}.tsx`))
);

/** Which set each block's components put it in, if any. */
const byComponent = new Map<string, string>();
for (const dir of dirs) {
  const components = declaredComponents(dir);
  const owner = SETS.find((set) => set.components.some((c) => components.includes(c)));
  if (owner) byComponent.set(dir, owner.key);
}

const lists = SETS.map(({ key, brand }) => {
  const fromComponents = dirs.filter((dir) => byComponent.get(dir) === key);

  // Only blocks no set has already claimed: a Polaris block that happens to
  // mention Sirius in a testimonial stays Polaris.
  const fromCopy = dirs.filter(
    (dir) =>
      !byComponent.has(dir) &&
      readFileSync(join(REGISTRY_DIR, dir, `${dir}.tsx`), "utf-8").includes(brand)
  );

  const names = Array.from(
    new Set([...fromComponents, ...fromCopy, ...(EXTRA[key] ?? [])])
  ).sort();

  console.log(
    `${key}: ${names.length} blocks (${fromComponents.length} by component, ${fromCopy.length} by copy)`
  );
  return { key, names };
});

const body = lists
  .map(({ key, names }) => `  ${key}: [\n${names.map((n) => `    "${n}",`).join("\n")}\n  ],`)
  .join("\n");

const output = `// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
// Generated by: bun run scripts/generate-block-sets.ts
// Source: the set's own components in each block's meta, plus the studio name in
// the demo copy for blocks that carry no set component

/** The studio sets the catalogue is built in. */
export type BlockSet = ${SETS.map((s) => `"${s.key}"`).join(" | ")};

/** Block names per set, sorted, as read from their demo copy. */
export const BLOCK_SETS: Record<BlockSet, readonly string[]> = {
${body}
};

/**
 * Every block in a studio set, for filtering a list down to the ones that share a
 * design language. A Set rather than an array: the home page asks this question
 * once per block it considers.
 */
export const STUDIO_SET_BLOCKS: ReadonlySet<string> = new Set(
  Object.values(BLOCK_SETS).flat()
);
`;

writeFileSync(OUTPUT, output);
console.log(`Wrote ${OUTPUT}`);
