/**
 * Generates lib/components.ts from registry-pieces/{slug}/{slug}.meta.ts and
 * lib/registry-components.ts from registry-components/{slug}/{slug}.meta.ts.
 *
 * Mirrors generate-blocks.ts but for the smaller "asset" components that are
 * designed to be dropped into block media slots (URL pills, status indicators,
 * mini widgets, etc.) and the design-system primitives (buttons, badges, ...)
 * that blocks are composed from.
 *
 * Usage: bun run scripts/generate-components.ts
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { ComponentMeta } from "../lib/component-types";

const REGISTRY_DIR = join(import.meta.dirname, "..", "registry-pieces");
const OUTPUT_COMPONENTS = join(import.meta.dirname, "..", "lib", "components.ts");
const OUTPUT_REGISTRY_COMPONENTS = join(import.meta.dirname, "..", "lib", "registry-components.ts");
/**
 * Barrel proxies that resolve `@/components/beste/piece/{name}` in dev to
 * the corresponding file in `registry-pieces/`. Same import path the shadcn
 * CLI installs to, so block source can use the install-target path everywhere.
 */
const PROXY_DIR = join(import.meta.dirname, "..", "components", "beste", "piece");
const PROXY_HEADER =
  "// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY\n" +
  "// Generated by: bun run scripts/generate-components.ts\n" +
  "// Re-exports the registry-piece so `@/components/beste/piece/{name}`\n" +
  "// resolves at dev time to the same path the shadcn CLI installs to.\n";

/**
 * registry-components/ holds reusable design-system primitives (button, badge,
 * input, ...). Their barrel proxies resolve `@/components/beste/component/{name}`
 * in dev to the corresponding file — the same path the shadcn CLI installs to.
 */
const UI_REGISTRY_DIR = join(import.meta.dirname, "..", "registry-components");
const UI_PROXY_DIR = join(import.meta.dirname, "..", "components", "beste", "component");
const UI_PROXY_HEADER =
  "// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY\n" +
  "// Generated by: bun run scripts/generate-components.ts\n" +
  "// Re-exports the registry-component so `@/components/beste/component/{name}`\n" +
  "// resolves at dev time to the same path the shadcn CLI installs to.\n";

interface CollectedMeta extends ComponentMeta {
  componentDir: string;
  componentName: string;
  demoName: string;
  toneOptions?: string[];
  /**
   * Whether the folder carries a `{name}.playground.ts` beside the meta. The
   * config itself is never read here — it is imported into the generated file,
   * so the playground stays typed and colocated instead of being flattened into
   * a string by this script.
   */
  hasPlayground?: boolean;
}

/**
 * Extract a `type Tone = "a" | "b" | ...` union from the source file.
 */
function extractToneOptions(filePath: string): string[] | undefined {
  if (!existsSync(filePath)) return undefined;
  const source = readFileSync(filePath, "utf-8");
  const match = source.match(/type\s+Tone\s*=\s*([^;]+);/);
  if (!match?.[1]) return undefined;
  const values = match[1].match(/"([^"]+)"/g);
  if (!values) return undefined;
  return values.map((v) => v.slice(1, -1));
}

/**
 * Convert a kebab-case slug to PascalCase (e.g. "browser-url" -> "BrowserUrl").
 */
function kebabToPascal(name: string): string {
  return name
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/**
 * Convert a kebab-case slug to camelCase (e.g. "browser-url" -> "browserUrl").
 */
function kebabToCamel(name: string): string {
  const pascal = kebabToPascal(name);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

/**
 * Extract the exported component name from a .tsx file.
 */
function extractComponentName(filePath: string): string | undefined {
  const content = readFileSync(filePath, "utf-8");
  const match = content.match(/^export\s+(?:function|const)\s+([A-Z][a-zA-Z0-9]+)(?:\s*[(:=])/m);
  return match?.[1];
}

/** Import meta files concurrently in batches to avoid fd exhaustion. */
const META_BATCH = 64;

/**
 * Write a file only when its content differs, to preserve mtimes (and thus
 * downstream incremental caches) when the generated output is unchanged.
 */
function writeIfChanged(path: string, content: string): boolean {
  if (existsSync(path) && readFileSync(path, "utf-8") === content) return false;
  writeFileSync(path, content, "utf-8");
  return true;
}

async function collectMetadata(registryDir: string): Promise<CollectedMeta[]> {
  if (!existsSync(registryDir)) {
    return [];
  }

  const dirs = readdirSync(registryDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort((a, b) => a.localeCompare(b, "en", { numeric: true }));

  const results: (CollectedMeta | null)[] = new Array(dirs.length).fill(null);

  for (let start = 0; start < dirs.length; start += META_BATCH) {
    const batch = dirs.slice(start, start + META_BATCH);
    await Promise.all(
      batch.map(async (dir, offset) => {
        const index = start + offset;
        const metaPath = join(registryDir, dir, `${dir}.meta.ts`);
        const componentPath = join(registryDir, dir, `${dir}.tsx`);

        if (!existsSync(metaPath)) {
          console.warn(`Warning: No .meta.ts file found for ${dir}`);
          return;
        }

        try {
          const module = await import(metaPath);
          const meta: ComponentMeta = module.meta;

          if (!meta) {
            console.warn(`Warning: No 'meta' export found in ${dir}.meta.ts`);
            return;
          }

          let componentName = meta.componentName;
          if (!componentName && existsSync(componentPath)) {
            componentName = extractComponentName(componentPath);
          }
          if (!componentName) {
            componentName = kebabToPascal(dir);
          }

          const demoName = `${kebabToCamel(dir)}Demo`;
          const toneOptions = extractToneOptions(componentPath);
          const hasPlayground = existsSync(join(registryDir, dir, `${dir}.playground.ts`));

          results[index] = {
            ...meta,
            componentDir: dir,
            componentName,
            demoName,
            toneOptions,
            hasPlayground,
          };
        } catch (error) {
          console.error(`Error importing ${dir}.meta.ts:`, error);
        }
      })
    );
  }

  return results.filter((m): m is CollectedMeta => m !== null);
}

/** `inspector-slider` -> `inspectorSliderPlayground`, the name it is imported as. */
function playgroundConst(dir: string): string {
  const [first, ...rest] = dir.split("-");
  return `${first}${rest.map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join("")}Playground`;
}

function buildEntries(metas: CollectedMeta[], withPlayground = false): string {
  return metas
    .map((m) => {
      const props = [
        `    name: "${m.name}"`,
        `    title: "${m.title}"`,
        `    description: "${escapeString(m.description)}"`,
        `    category: "${m.category}"`,
        `    component: ${m.componentName}`,
        `    demoProps: ${m.demoName}`,
      ];
      if (m.registryDependencies?.length) {
        const deps = m.registryDependencies.map((d) => `"${d}"`).join(", ");
        props.push(`    registryDependencies: [${deps}]`);
      }
      if (m.registryComponents?.length) {
        const nested = m.registryComponents.map((d) => `"${d}"`).join(", ");
        props.push(`    registryComponents: [${nested}]`);
      }
      if (m.hidden) props.push(`    hidden: true`);
      if (m.toneOptions?.length) {
        const tones = m.toneOptions.map((t) => `"${t}"`).join(", ");
        props.push(`    variants: { tone: [${tones}] }`);
      }
      // JSON.stringify keeps the multi-line snippet on one safely-escaped line.
      if (m.usage) props.push(`    usage: ${JSON.stringify(m.usage)}`);
      if (m.usageBase) props.push(`    usageBase: ${JSON.stringify(m.usageBase)}`);
      if (m.isPro) props.push(`    isPro: true`);
      // Only registry-components import their playgrounds, so only that file may
      // name one. A piece with a playground file would otherwise emit an
      // identifier nothing imported.
      if (withPlayground && m.hasPlayground) {
        props.push(`    playground: ${playgroundConst(m.componentDir)}`);
      }
      return `  {\n${props.join(",\n")},\n  }`;
    })
    .join(",\n");
}

function generateComponentsTs(metas: CollectedMeta[]): string {
  const imports = metas
    .map(
      (m) =>
        `import { ${m.componentName}, ${m.demoName} } from "@/registry-pieces/${m.componentDir}/${m.componentDir}";`
    )
    .join("\n");

  const entries = buildEntries(metas);

  return `// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
// Generated by: bun run scripts/generate-components.ts
// Source: registry-pieces/{name}/{name}.meta.ts files

import type { ComponentType } from "react";

${imports}

export interface ComponentMeta {
  name: string;
  title: string;
  description: string;
  category: string;
  component: ComponentType<any>;
  demoProps: any;
  /** shadcn/ui component dependencies (e.g., ["avatar"]) */
  registryDependencies?: string[];
  /** Live-tweakable variants exposed in the preview (e.g., tone) */
  variants?: { tone?: string[] };
  /** Hand-written "Import & use" snippet documenting the props API */
  usage?: string;
  /** Base UI-flavor snippet (render prop); falls back to usage */
  usageBase?: string;
  /** If true, the component is Pro with obfuscated source code */
  isPro?: boolean;
  /** Other registry-components bundled with this one on install */
  registryComponents?: string[];
  /** If true, excluded from showcase listings (still installable) */
  hidden?: boolean;
}

const _components: ComponentMeta[] = [
${entries}
];

export const components = _components;

export function getComponent(name: string): ComponentMeta | undefined {
  return components.find((component) => component.name === name);
}
`;
}

function generateRegistryComponentsTs(metas: CollectedMeta[]): string {
  const imports = metas
    .map(
      (m) =>
        `import { ${m.componentName}, ${m.demoName} } from "@/registry-components/${m.componentDir}/${m.componentDir}";`
    )
    .join("\n");

  // One line per component that ships a playground, aliased so the entry below
  // can name it without the file having to know about this script.
  const playgroundImports = metas
    .filter((m) => m.hasPlayground)
    .map(
      (m) =>
        `import { playground as ${playgroundConst(m.componentDir)} } from "@/registry-components/${m.componentDir}/${m.componentDir}.playground";`
    )
    .join("\n");

  const entries = buildEntries(metas, true);

  return `// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
// Generated by: bun run scripts/generate-components.ts
// Source: registry-components/{name}/{name}.meta.ts files

import type { ComponentType } from "react";

import type { PlaygroundConfig } from "@/lib/playground-types";

${imports}
${playgroundImports}

export interface RegistryComponentMeta {
  name: string;
  title: string;
  description: string;
  category: string;
  component: ComponentType<any>;
  demoProps: any;
  /** shadcn/ui component dependencies (e.g., ["button"]) */
  registryDependencies?: string[];
  /** Live-tweakable variants exposed in the preview (e.g., tone) */
  variants?: { tone?: string[] };
  /** Hand-written "Import & use" snippet documenting the props API */
  usage?: string;
  /** Base UI-flavor snippet (render prop); falls back to usage */
  usageBase?: string;
  /** If true, the component is Pro with obfuscated source code */
  isPro?: boolean;
  /** Other registry-components bundled with this one on install */
  registryComponents?: string[];
  /** If true, excluded from showcase listings (still installable) */
  hidden?: boolean;
  /** Docs playground, from {name}.playground.ts beside the component */
  playground?: PlaygroundConfig;
}

const _allRegistryComponents: RegistryComponentMeta[] = [
${entries}
];

/** Every registry-component, including hidden infrastructure ones. */
export const allRegistryComponents = _allRegistryComponents;

/** Components shown on showcase surfaces (hidden ones excluded). */
export const registryComponents = _allRegistryComponents.filter(
  (component) => !component.hidden
);

export function getRegistryComponent(
  name: string
): RegistryComponentMeta | undefined {
  return _allRegistryComponents.find((component) => component.name === name);
}
`;
}

function escapeString(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

async function main() {
  console.log("Collecting metadata from registry-pieces/*/*.meta.ts...");
  const metas = await collectMetadata(REGISTRY_DIR);

  if (metas.length === 0) {
    console.warn("No component metadata files found — writing empty components.ts");
  } else {
    console.log(`Found ${metas.length} components`);
  }

  console.log("Generating lib/components.ts...");
  const content = generateComponentsTs(metas);
  writeIfChanged(OUTPUT_COMPONENTS, content);

  console.log("Generating components/beste/piece/*.tsx proxies...");
  if (!existsSync(PROXY_DIR)) {
    mkdirSync(PROXY_DIR, { recursive: true });
  }
  for (const m of metas) {
    const proxyPath = join(PROXY_DIR, `${m.componentDir}.tsx`);
    const proxy = `${PROXY_HEADER}\nexport * from "@/registry-pieces/${m.componentDir}/${m.componentDir}";\n`;
    writeIfChanged(proxyPath, proxy);
  }

  console.log("Collecting metadata from registry-components/*/*.meta.ts...");
  const uiMetas = await collectMetadata(UI_REGISTRY_DIR);

  console.log("Generating lib/registry-components.ts...");
  writeIfChanged(OUTPUT_REGISTRY_COMPONENTS, generateRegistryComponentsTs(uiMetas));

  console.log("Generating components/beste/component/*.tsx proxies...");
  let uiProxyCount = 0;
  if (existsSync(UI_REGISTRY_DIR)) {
    if (!existsSync(UI_PROXY_DIR)) {
      mkdirSync(UI_PROXY_DIR, { recursive: true });
    }
    const uiDirs = readdirSync(UI_REGISTRY_DIR, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name)
      .sort((a, b) => a.localeCompare(b, "en", { numeric: true }));
    for (const dir of uiDirs) {
      if (!existsSync(join(UI_REGISTRY_DIR, dir, `${dir}.tsx`))) continue;
      const proxyPath = join(UI_PROXY_DIR, `${dir}.tsx`);
      const proxy = `${UI_PROXY_HEADER}\nexport * from "@/registry-components/${dir}/${dir}";\n`;
      writeIfChanged(proxyPath, proxy);
      uiProxyCount++;
    }
  }

  console.log("Done! Generated:");
  console.log(`  - lib/components.ts (${metas.length} components)`);
  console.log(`  - lib/registry-components.ts (${uiMetas.length} components)`);
  console.log(`  - components/beste/piece/*.tsx (${metas.length} proxies)`);
  console.log(`  - components/beste/component/*.tsx (${uiProxyCount} proxies)`);
}

main().catch(console.error);
