/**
 * Generates lib/block-sets.ts: which blocks belong to which studio set.
 *
 * There is no `set` field in BlockMeta, and there deliberately is not one in the
 * titles or descriptions either — a set name is an internal label and has no place
 * in what a reader or a search engine sees. The one place it does legitimately
 * appear is the demo copy, where the set's fictional studio is the brand being
 * shown: "Auralis is an independent design studio…". That is what this script
 * reads.
 *
 * It is a heuristic, and an honest one: a block built in a set whose demo copy
 * never names the studio will not be found here. When that happens, the fix is to
 * add the name to EXTRA below rather than to loosen the match.
 *
 * Usage: bun run scripts/generate-block-sets.ts
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const REGISTRY_DIR = join(import.meta.dirname, "..", "registry");
const OUTPUT = join(import.meta.dirname, "..", "lib", "block-sets.ts");

/** The sets to look for, and the word that identifies each one in demo copy. */
const SETS = [
  { key: "auralis", brand: "Auralis" },
  { key: "polaris", brand: "Polaris" },
  { key: "sirius", brand: "Sirius" },
] as const;

/** Blocks that belong to a set but never say its name. Add by hand. */
const EXTRA: Record<string, string[]> = {
  auralis: [],
  polaris: [],
  // Built in the Sirius language, but its demo copy is a product screen with no
  // studio name anywhere in it.
  sirius: ["feature237"],
};

function collect(brand: string): string[] {
  const found: string[] = [];
  for (const dir of readdirSync(REGISTRY_DIR)) {
    const file = join(REGISTRY_DIR, dir, `${dir}.tsx`);
    if (!existsSync(file)) continue;
    if (readFileSync(file, "utf-8").includes(brand)) found.push(dir);
  }
  return found;
}

const lists = SETS.map(({ key, brand }) => {
  const names = Array.from(new Set([...collect(brand), ...(EXTRA[key] ?? [])])).sort();
  console.log(`${key}: ${names.length} blocks`);
  return { key, names };
});

const body = lists
  .map(({ key, names }) => `  ${key}: [\n${names.map((n) => `    "${n}",`).join("\n")}\n  ],`)
  .join("\n");

const output = `// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
// Generated by: bun run scripts/generate-block-sets.ts
// Source: the set's own studio name in each block's demo copy

/** The studio sets the catalogue is built in. */
export type BlockSet = ${SETS.map((s) => `"${s.key}"`).join(" | ")};

/** Block names per set, sorted, as read from their demo copy. */
export const BLOCK_SETS: Record<BlockSet, readonly string[]> = {
${body}
};

/**
 * Every block in a studio set, for filtering a list down to the ones that share a
 * design language. A Set rather than an array: the home page asks this question
 * once per block it considers.
 */
export const STUDIO_SET_BLOCKS: ReadonlySet<string> = new Set(
  Object.values(BLOCK_SETS).flat()
);
`;

writeFileSync(OUTPUT, output);
console.log(`Wrote ${OUTPUT}`);
